import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const API_BASE="https://api.livetennisapi.com/api/public/v1";
const API_KEY=Deno.env.get("LIVE_TENNIS_API_KEY");
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET, OPTIONS"};
type Obj=Record<string,unknown>; type CourtTour="ATP"|"WTA"|"CHALLENGER"|"ITF"|"JUNIORS"|"UNKNOWN";
function json(body:unknown,status=200,extra:HeadersInit={}){return new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json; charset=utf-8",...corsHeaders,...extra}})}
function asObj(v:unknown):Obj{return v&&typeof v==="object"&&!Array.isArray(v)?v as Obj:{}}
function mapTour(v:unknown):CourtTour{const s=String(v??"").toLowerCase();if(s==="atp"||s.startsWith("atp_")||s==="challenger_men")return"ATP";if(s==="wta"||s.startsWith("wta_"))return"WTA";if(s==="challenger")return"CHALLENGER";if(s==="itf")return"ITF";if(s==="juniors")return"JUNIORS";return"UNKNOWN"}
function mapSurface(v:unknown):"hard"|"clay"|"grass"|"carpet"|"unknown"{const s=String(v??"").toLowerCase();if(s.includes("hard"))return"hard";if(s.includes("clay"))return"clay";if(s.includes("grass"))return"grass";if(s.includes("carpet"))return"carpet";return"unknown"}
function playerRef(raw:unknown,fallbackTour:CourtTour){const p=asObj(raw),mt=mapTour(p.tour);return{id:p.id==null?"":String(p.id),name:String(p.name??"Unknown player"),tour:mt==="UNKNOWN"?fallbackTour:mt,countryCode:p.country==null?undefined:String(p.country),ranking:typeof p.ranking==="number"?p.ranking:undefined,rankingPoints:typeof p.ranking_points==="number"?p.ranking_points:undefined,rankingMovement:p.ranking_movement==null?undefined:String(p.ranking_movement),hand:p.hand==null?undefined:String(p.hand),birthday:p.birthday==null?undefined:String(p.birthday),backhand:typeof p.backhand==="number"?p.backhand:undefined,isDoublesTeam:p.is_doubles_team===true}}
function normalizePlayer(raw:Obj){const tour=mapTour(raw.tour);return{...playerRef(raw,tour),rawTour:raw.tour==null?undefined:String(raw.tour),stats:raw.stats&&typeof raw.stats==="object"?raw.stats:undefined}}
function normalizeMatch(raw:Obj,fallbackStatus:"live"|"scheduled"){const tour=mapTour(raw.tour),players=asObj(raw.players),draw=String(raw.draw??(raw.is_doubles===true?"doubles":"singles")).toLowerCase(),ps=String(raw.status??"").toLowerCase(),score=asObj(raw.score);const status=ps==="live"?"live":ps==="upcoming"?"scheduled":ps==="completed"?"completed":ps==="cancelled"?"cancelled":fallbackStatus;const sets=Array.isArray(score.sets)?score.sets:Array.isArray(raw.sets)?raw.sets:[];const games=Array.isArray(score.games)?score.games:Array.isArray(raw.games)?raw.games:[];const points=Array.isArray(score.points)?score.points:Array.isArray(raw.points)?raw.points:[];const server=typeof score.server==="number"?score.server:typeof raw.server==="number"?raw.server:null;const isTiebreak=typeof score.is_tiebreak==="boolean"?score.is_tiebreak:typeof raw.is_tiebreak==="boolean"?raw.is_tiebreak:false;return{id:raw.id==null?"":String(raw.id),tournamentId:raw.tournament_id==null?"":String(raw.tournament_id),tournamentName:String(raw.tournament??"Unknown tournament"),tour,eventType:draw.includes("double")?"doubles":"singles",round:raw.round==null?undefined:String(raw.round),roundCode:raw.round_code==null?undefined:String(raw.round_code),surface:mapSurface(raw.surface),indoor:typeof raw.indoor==="boolean"?raw.indoor:undefined,scheduledAt:raw.scheduled_time==null?"":String(raw.scheduled_time),status,eventStatus:raw.event_status==null?undefined:String(raw.event_status),home:playerRef(players.p1,tour),away:playerRef(players.p2,tour),sets,games,points,server,isTiebreak}}
async function providerGet(path:string){if(!API_KEY)return{ok:false as const,status:503,body:{error:"provider_not_configured"}};const r=await fetch(`${API_BASE}${path}`,{headers:{Authorization:`Bearer ${API_KEY}`,Accept:"application/json"}}),text=await r.text();let body:unknown;try{body=text?JSON.parse(text):null}catch{body={raw:text}}if(!r.ok)return{ok:false as const,status:r.status,body:{error:r.status===403?"not_available_on_free_provider":"provider_error",providerStatus:r.status,details:body},retryAfter:r.headers.get("retry-after")};return{ok:true as const,body}}
function rows(body:unknown):Obj[]{if(Array.isArray(body))return body as Obj[];const b=asObj(body);for(const k of["data","matches","fixtures","results"])if(Array.isArray(b[k]))return b[k] as Obj[];return[]}
function isMainTour(m:{tour:CourtTour}){return m.tour==="ATP"||m.tour==="WTA"}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(req.method!=="GET")return json({error:"method_not_allowed"},405);const url=new URL(req.url),pathRoute=url.pathname.split("/").filter(Boolean).at(-1),route=url.searchParams.get("route")??(pathRoute==="court-tennis"?"today":pathRoute)??"today";
if(route==="health"){const r=await providerGet("/health");return r.ok?json({ok:true,provider:"live-tennis-api",providerResponse:r.body}):json(r.body,r.status)}
if(route==="players"){const search=(url.searchParams.get("search")??"").trim();if(search.length<2)return json({players:[]});const r=await providerGet(`/players?search=${encodeURIComponent(search)}&limit=30`);if(!r.ok)return json(r.body,r.status,r.retryAfter?{"Retry-After":r.retryAfter}:{});const players=rows(r.body).map(normalizePlayer).filter(p=>(p.tour==="ATP"||p.tour==="WTA")&&!p.isDoublesTeam).slice(0,20);return json({provider:"live-tennis-api",fetchedAt:new Date().toISOString(),players})}
if(route==="player"){const id=url.searchParams.get("id");if(!id)return json({error:"missing_id"},400);const[r,upcoming]=await Promise.all([providerGet(`/players/${encodeURIComponent(id)}`),providerGet(`/matches?status=upcoming&player=${encodeURIComponent(id)}&limit=10`)]);if(!r.ok)return json(r.body,r.status,r.retryAfter?{"Retry-After":r.retryAfter}:{});const raw=asObj(asObj(r.body).data??r.body),player=normalizePlayer(raw);if(!isMainTour(player))return json({error:"not_main_tour"},404);const nextMatch=upcoming.ok?rows(upcoming.body).map(m=>normalizeMatch(m,"scheduled")).filter(isMainTour).sort((a,b)=>a.scheduledAt.localeCompare(b.scheduledAt))[0]:undefined;return json({provider:"live-tennis-api",fetchedAt:new Date().toISOString(),player,nextMatch})}
if(route==="tournament"){const id=url.searchParams.get("id");if(!id)return json({error:"missing_id"},400);const r=await providerGet(`/tournaments/${encodeURIComponent(id)}`);if(!r.ok)return json(r.body,r.status,r.retryAfter?{"Retry-After":r.retryAfter}:{});const raw=asObj(asObj(r.body).data??r.body),tour=mapTour(raw.tour);if(tour!=="ATP"&&tour!=="WTA")return json({error:"not_main_tour"},404);return json({provider:"live-tennis-api",fetchedAt:new Date().toISOString(),tournament:{id:String(raw.id??id),name:String(raw.name??"Unknown tournament"),tour,surface:mapSurface(raw.surface),indoor:raw.indoor===true,city:raw.city==null?undefined:String(raw.city),country:raw.country==null?undefined:String(raw.country),category:raw.category==null?undefined:String(raw.category)}})}
if(route==="match"){const id=url.searchParams.get("id");if(!id)return json({error:"missing_id"},400);const r=await providerGet(`/matches/${encodeURIComponent(id)}`);if(!r.ok)return json(r.body,r.status,r.retryAfter?{"Retry-After":r.retryAfter}:{});const b=asObj(r.body),raw=asObj(b.data??b.match??r.body),match=normalizeMatch(raw,"scheduled");return isMainTour(match)?json({provider:"live-tennis-api",fetchedAt:new Date().toISOString(),match}):json({error:"not_main_tour"},404)}
if(route==="today"){const from=url.searchParams.get("from"),to=url.searchParams.get("to"),draw=url.searchParams.get("draw")==="doubles"?"doubles":"singles";if(!from||!to||Number.isNaN(Date.parse(from))||Number.isNaN(Date.parse(to))||Date.parse(from)>Date.parse(to))return json({error:"bad_range"},400);const q=`from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}&draw=${draw}&limit=200`;const[live,upcoming]=await Promise.all([providerGet(`/matches?status=live&${q}`),providerGet(`/matches?status=upcoming&${q}`)]);for(const r of[live,upcoming])if(!r.ok)return json(r.body,r.status,r.retryAfter?{"Retry-After":r.retryAfter}:{});const liveMatches=rows(live.body).map(m=>normalizeMatch(m,"live")).filter(isMainTour).filter(m=>m.eventType===draw),liveIds=new Set(liveMatches.map(m=>m.id));const upcomingMatches=rows(upcoming.body).map(m=>normalizeMatch(m,"scheduled")).filter(isMainTour).filter(m=>m.eventType===draw).filter(m=>!liveIds.has(m.id)).sort((a,b)=>a.scheduledAt.localeCompare(b.scheduledAt));return json({provider:"live-tennis-api",fetchedAt:new Date().toISOString(),range:{from,to},draw,live:liveMatches,upcoming:upcomingMatches,capabilities:{live:true,dateFilteredMatches:true,localDayRange:true,upcoming:true,matchDetail:true,players:true,playerDetail:true,tournamentDetail:true,completedHistory:false,h2h:false,fullRankings:false}})}return json({error:"not_found"},404)});
